Repository najibjodiansyah/group5-capstone-project, pull requests merged in 2022-03, with the labels that each got.

#10 fix status when create application, lower case all status
  delivery/controllers/application/application.go
Labels: help wanted

#11 add procurement feature
  delivery/controllers/procurement/formatter.go
  delivery/controllers/procurement/procurement.go
  delivery/routes/route.go
  entities/procurement.go
  main.go
  repository/item/item.go
  repository/procurement/interface.go
  repository/procurement/procurement.go
Labels: enhancement

#12 add order by descending for asset
  repository/asset/asset.go
Labels: enhancement

#13 add some endpoint
  delivery/controllers/category/category.go
  delivery/controllers/statistic/statistic.go
  delivery/routes/route.go
  entities/category.go
  entities/statistic.go
  main.go
  repository/category/category.go
  repository/category/interface.go
  repository/item/item.go
  repository/statistic/interface.go
  repository/statistic/statistic.go
Labels: enhancement

#14 revise get user application history and activity
  README.md
  repository/application/application.go
  repository/application/interface.go
Labels: bug

#18 add duration time
  delivery/controllers/application/application.go
  delivery/controllers/application/formatter.go
  entities/applications.go
  repository/application/application.go
  repository/application/interface.go
Labels: enhancement

#19 cleaning check
  delivery/controllers/application/application.go
  delivery/controllers/application/formatter.go
  delivery/controllers/asset/asset.go
  delivery/controllers/user/user.go
  repository/application/application.go
  repository/asset/asset.go
Labels: documentation

#25 fix bug status asset
  repository/asset/asset.go
Labels: bug
